- hosts: web
  become: true
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
    notify:
    - Restart httpd
  - name: Copy index.html
    copy:
      src: index.html
      dest: /var/www/html
  handlers:
  - name: Restart httpd
    service:
      name: httpd
      state: restarted

